version: "3.9"
services:
  postgres:
    image: postgres:12
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=cst4Ever
    - POSTGRES_DB=mypostgres
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://postgres:cst4Ever@postgres:5432/mypostgres?sslmode=disable
    depends_on:
      - postgres
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]



