name: deploy to production

on:
  push:
    branches: [ main ]


jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code into the Go module diectory
        uses: actions/checkout@v2
      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ailanz/simple_bank:latest